modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/TropheusJ/stonecutter-recipe-tags/issues"
license = "MIT"

[[mods]]
modId = "stonecutter_recipe_tags"
version = "${version}"
displayName = "Stonecutter Recipe Tags"
authors = "Tropheus Jay, Pepper_Bell"
description = '''
Allows for creation of stonecutter recipes with tags, saving on JSON files.
'''
logoFile = "icon.png"

[[dependencies.stonecutter_recipe_tags]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stonecutter_recipe_tags]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
